version: "3.9"

services:
  app:
    build: .
    container_name: comsitec_app
    ports:
      - "9876:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: comsitec_db_business
      DB_USER: comsitec
      DB_PASS: comsitec123

  db:
    image: mysql:5.7
    container_name: comsitec_db
    restart: always
    environment:
      MYSQL_DATABASE: comsitec_db_business
      MYSQL_USER: comsitec
      MYSQL_PASSWORD: comsitec123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
